/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicplatform;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DHRUV
 */
public class AddSongs extends javax.swing.JFrame {

    /**
     * Creates new form AddSongs
     */
    public AddSongs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton1)
                .addContainerGap(750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(128, 128, 128))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public void insertSong(String song_artist, String song_title, File imageFile, int duration, File audioFile, int trackid) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/new", "root", "Dhruv@99269!")) {
            String query = "INSERT INTO songs (trackid, song_cover_image, song_title, song_audio, song_artist, song_duration) VALUES (?, ?, ?, ?, ?, ?)";
            try (java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                byte[] imageBytes = new byte[(int) imageFile.length()];
                byte[] audioBytes = new byte[(int) audioFile.length()];
                try (FileInputStream fis = new FileInputStream(imageFile)) {
                    fis.read(imageBytes);
                    fis.read(audioBytes);
                }

                statement.setString(5, song_artist);
                statement.setString(3, song_title);
                statement.setInt(6, duration);
                statement.setInt(1, trackid);
                statement.setBytes(2, imageBytes);
                statement.setBytes(4, audioBytes);

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println(song_title + " inserted successfully!");
                    dispose();
                    Songs sng = new Songs();
                    sng.setVisible(true);
                } else {
                    System.err.println("Failed to insert song.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddSongs.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException e) {
            System.err.println("Error inserting song: " + e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(AddSongs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    public void insertSong(String title, File imageFile) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "Dhruv@99269!")) {
            String query = "INSERT INTO albums (album_name, album_cover_image) VALUES (?,?)";
            try (java.sql.PreparedStatement statement = connection.prepareStatement(query)) {
                byte[] imageBytes = new byte[(int) imageFile.length()];
                try (FileInputStream fis = new FileInputStream(imageFile)) {
                    fis.read(imageBytes);
                }
                
                statement.setString(1, title);
                statement.setBytes(2, imageBytes);
                
                // Read audio file as bytes
                byte[] audioBytes = new byte[(int) imageFile.length()];
                try (FileInputStream fis = new FileInputStream(imageFile)) {
                    fis.read(audioBytes);
                }

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println("album inserted successfully!");
                    dispose();
                    Songs sng = new Songs();
                    sng.setVisible(true);
                } else {
                    System.err.println("Failed to insert song.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddSongs.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException e) {
            System.err.println("Error inserting song: " + e.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(AddSongs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*String imagePath = "D:/songs/baatonkoteri.jpg";
        String songTitle = "phir se ud chala";
        String songArtist = "kk, tulsi kumar";
        int dur = 200;
        int sid = 65;
        String audioPath = "C:/Users/DHRUV/Downloads/Tune Jo Na Kaha - New York 128 Kbps.mp3";
        insertSong(songArtist, songTitle, new File(imagePath), dur, new File(audioPath), sid);*/                                         
        // TODO add your handling code here:
        String imagePath = "D:/songs/Albums/Most Played All Time/1 album cover.jpeg";
        String albumTitle = "Most Played All Time";        
        insertSong(albumTitle, new File(imagePath));        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSongs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
