/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicplatform;

import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DHRUV
 */
public class NewPlayer extends javax.swing.JFrame {

    long total_length;
    long pause;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    File myFile = null;

    public NewPlayer() {
        initComponents();
    }

    private void loadAndPlaySongFromDatabase() throws Exception {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        try {
            // Connect to the database
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "Dhruv@99269!");

            // Prepare a statement to retrieve the song file
            String sql = "SELECT song_audio FROM tracks WHERE trackid = ?";
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setInt(1, 30); // Assuming trackid is 30

            // Execute the query
            resultSet = preparedStatement.executeQuery();

            // Process the result set
            if (resultSet.next()) {
                // Retrieve the song file as a byte array
                byte[] songData = resultSet.getBytes("song_audio");

                // Play the song
                playSong(songData);
            } else {
                JOptionPane.showMessageDialog(this, "Song not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(NewPlayer.class.getName()).log(Level.SEVERE, "Error loading song from database", ex);
            throw ex; // Propagate the exception
        } finally {
            // Close resources in the reverse order of their creation
            if (resultSet != null) {
                resultSet.close();
            }
            if (preparedStatement != null) {
                preparedStatement.close();
            }
            if (connection != null) {
                connection.close();
            }
        }
    }

    private void playSong(byte[] songData) throws Exception {
        try (InputStream songInputStream = new ByteArrayInputStream(songData)) {
            player = new Player(songInputStream);
            new Thread(() -> {
                try {
                    player.play();
                } catch (JavaLayerException ex) {
                    Logger.getLogger(NewPlayer.class.getName()).log(Level.SEVERE, "Error playing the song", ex);
                    JOptionPane.showMessageDialog(NewPlayer.this, "Error playing the song.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }).start();
        } catch (Exception ex) {
            Logger.getLogger(NewPlayer.class.getName()).log(Level.SEVERE, "Error creating song input stream", ex);
            throw ex; // Propagate the exception
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playbtn = new javax.swing.JButton();
        pausebtn = new javax.swing.JButton();
        resumebtn = new javax.swing.JButton();
        stopbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playbtn.setText("Play");
        playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playbtnActionPerformed(evt);
            }
        });

        pausebtn.setText("Pause");
        pausebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausebtnActionPerformed(evt);
            }
        });

        resumebtn.setText("Resume");
        resumebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumebtnActionPerformed(evt);
            }
        });

        stopbtn.setText("Stop");
        stopbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playbtn)
                        .addGap(90, 90, 90)
                        .addComponent(pausebtn)
                        .addGap(77, 77, 77)
                        .addComponent(resumebtn)
                        .addGap(81, 81, 81)
                        .addComponent(stopbtn)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playbtn)
                    .addComponent(pausebtn)
                    .addComponent(resumebtn)
                    .addComponent(stopbtn))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playbtnActionPerformed
        // TODO add your handling code here:

        // Load and play song from database
        try {
            loadAndPlaySongFromDatabase();
        } catch (Exception ex) {
            Logger.getLogger(NewPlayer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error loading and playing the song.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_playbtnActionPerformed

    private void resumebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resumebtnActionPerformed

    private void pausebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausebtnActionPerformed
        // TODO add your handling code here:
        if (player != null) {
            try {
                pause = FIS.available();
                player.close();
            } catch (IOException ex) {
                Logger.getLogger(NewPlayer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_pausebtnActionPerformed

    private void stopbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pausebtn;
    private javax.swing.JButton playbtn;
    private javax.swing.JButton resumebtn;
    private javax.swing.JButton stopbtn;
    // End of variables declaration//GEN-END:variables
}
